FROM nginx:alpine

ARG SOURCE_COMMIT
ARG SOURCE_TAG
LABEL org.opencontainers.image.revision=$SOURCE_COMMIT
LABEL org.opencontainers.image.version=$SOURCE_TAG


COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./www /var/www/html

RUN echo "$(date +%s)" >> /etc/container_build_timestamp
RUN echo $SOURCE_COMMIT >> /etc/container_SOURCE_COMMIT
RUN echo $SOURCE_TAG >> /etc/container_SOURCE_TAG