
services:

  nginxfpm:
    build:
      context: .
      dockerfile: Dockerfile.nginxfpm
    volumes:
      - ./www:/var/www/html
      - ./config/opcache.local.ini:/usr/local/etc/php/conf.d/opcache.ini

  php:
    build: .
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: dle
      MYSQL_USER: dleuser
      MYSQL_PASSWORD: dlepass
    ports:
      - "14588:3306"
    volumes:
      - db_data:/var/lib/mysql

  db-sync:
    build:
      context: .
      dockerfile: Dockerfile.dbsync
    environment:
      - DO_HOST=127.0.0.1
      - DO_PORT=7777
      - DO_USER=doadmin
      # - DO_PASS=
      - DO_DB=cis_dle
      - LOCAL_HOST=db
      - LOCAL_USER=dleuser
      - LOCAL_PASS=dlepass
      - LOCAL_DB=dle

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron

volumes:
  db_data: