name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit and tag
        id: vars
        run: |
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image FPM
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.fpm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-fpm:latest
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}

      - name: Build and push Docker image NGINX
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-nginx:latest
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}

      - name: Notify Telegram
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="✅ *Docker образы успешно опубликованы!*

              📦 Образы:
              - \`${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-fpm:latest\`
              - \`${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-nginx:latest\`

              🧑 Коммит: \`${{ steps.vars.outputs.commit }}\`
              🏷️ Тег: \`${{ steps.vars.outputs.tag }}\`
              🔗 [GitHub Actions Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="❌ *Ошибка в GitHub Actions Workflow!*

              🧑 Автор: ${{ github.actor }}
              📝 Commit: \`${{ github.sha }}\`
              🔗 [Смотреть лог ошибки](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"