name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit and tag
        id: vars
        run: |
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image FPM
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.fpm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-fpm:latest
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}

      - name: Build and push Docker image NGINX
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-nginx:latest
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}